#ifndef _BSE_PHYSICSCOMMONS_H_INCLUDED
#define _BSE_PHYSICSCOMMONS_H_INCLUDED

#define BSE_DEBUG_HELPERS // comment for delivery
#ifdef BSE_DEBUG_HELPERS
# define BSE_DEBUG_HELPERS_STORECONTACTS
#endif

#endif // _BSE_PHYSICSCOMMONS_H_INCLUDED